### ISSUE TITLE
[cuDNN] Add lowering from cudnn.relu + relu custom call

### ISSUE THREAD

**Issue by ezhulenev** [openxla/openxla-nvgpu#123]
`Relu` operation should be supported by cudnn compiler plugin and runtime.

**Comment by ezhulenev** [comment]
We actually already have custom call here: https://github.com/openxla/openxla-nvgpu/blob/628fc75bcfe00c0ab2551824914a896668f21909/runtime/src/openxla/runtime/nvgpu/cudnn/cudnn_module.cpp#L195-L200 but no correspodning lowering here: https://github.com/openxla/openxla-nvgpu/blob/main/compiler/src/openxla/compiler/nvgpu/Dialect/CUDNN/Conversion/ConvertCUDNNToRuntime.cpp

**Comment by bviyer** [comment]
I think this bug can be closed since [9c5504a](https://github.com/bviyer/openxla-nvgpu/commit/9c5504a3be8350938de628a1531d547eb848f28c) is committed.
